apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: plant-api
  name: plant-api
  namespace: wp-dev
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: plant-api:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    dockerStrategy:
      dockerfilePath: Containerfile
    type: Docker
  successfulBuildsHistoryLimit: 5
